### ISSUE TITLE
Pin go-billy and afero dependencies

### ISSUE THREAD

**Issue by c4milo** [Maldris/go-billy-afero#2]
Thanks for adding the license @Maldris. I'm currently using go-billy v5 and Afero 1.3.3. This library seems to be using whatever is latest in master from both repos. Would it be possible to pin their versions using Go modules?

**Comment by Maldris** [comment]
Sorry for the late response, I've had a busy two weeks with work and this kept slipping my mind.

I know a private project of a friend uses this repo with an older dependency management tool that conflicts with modules. I'll try to work with them to migrate to modules, add some tests to this package (been meaning to do that for a while) and add modules here.

I'll hopefully get that done this weekend, or next week. Thanks for being patient.

**Comment by Maldris** [comment]
Turned out they had made a lot of progress on converting to modules, so I actually got the tests and module build setup done today.

I hope this helps, let me know if you notice anything else I've missed, I haven't been looking at this repo much lately, it wouldn't surprise me if I've overlooked something
